/**
 * Filesystem layout owner for ~/.claude/afterglow/
 *
 *   ~/.claude/afterglow/
 *   ├─ config.yml                ← env config (embedding model, storage root, …)
 *   ├─ registry.json             ← index of all agents
 *   ├─ councils/                 ← council + peer-ask transcripts (markdown)
 *   └─ agents/<slug>/
 *      ├─ persona.json
 *      ├─ system-prompt.md
 *      ├─ mcp-allowlist.yml
 *      ├─ consent.md
 *      ├─ history.log
 *      ├─ knowledge/             ← raw source files (PDF / md / txt / …)
 *      └─ embeddings/            ← derived RAG index (jsonl chunks for the PoC)
 */
import { promises as fs } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import type { Persona } from './persona.js';

/**
 * Resolved on every call (not at module load) so tests can flip
 * AFTERGLOW_ROOT per-test without re-importing the module.
 */
export function rootDir(): string {
  const envRoot = process.env.AFTERGLOW_ROOT;
  if (envRoot) return resolve(envRoot);
  return join(homedir(), '.claude', 'afterglow');
}

export function configPath(): string {
  return join(rootDir(), 'config.yml');
}

export function registryPath(): string {
  return join(rootDir(), 'registry.json');
}

export function councilsDir(): string {
  return join(rootDir(), 'councils');
}

export function agentsDir(): string {
  return join(rootDir(), 'agents');
}

export function agentDir(slug: string): string {
  return join(agentsDir(), slug);
}

export function archiveDir(): string {
  return join(rootDir(), 'archive');
}

export function archivedAgentDir(slug: string): string {
  return join(archiveDir(), slug);
}

export function personaPath(slug: string): string {
  return join(agentDir(slug), 'persona.json');
}

export function systemPromptPath(slug: string): string {
  return join(agentDir(slug), 'system-prompt.md');
}

export function consentPath(slug: string): string {
  return join(agentDir(slug), 'consent.md');
}

export function historyLogPath(slug: string): string {
  return join(agentDir(slug), 'history.log');
}

export function knowledgeDir(slug: string): string {
  return join(agentDir(slug), 'knowledge');
}

export function embeddingsDir(slug: string): string {
  return join(agentDir(slug), 'embeddings');
}

/* --------------------------------------------------------------- */
/* Slug validation                                                 */
/* --------------------------------------------------------------- */

const SLUG_RE = /^[a-z0-9][a-z0-9-]{0,30}[a-z0-9]$/;
const SLUG_RE_SINGLE = /^[a-z0-9]$/;

export class InvalidSlugError extends Error {
  constructor(slug: string) {
    super(`Invalid slug: "${slug}". Use 1-32 lowercase letters/digits/hyphens, starting and ending with a letter or digit.`);
    this.name = 'InvalidSlugError';
  }
}

export class AgentNotFoundError extends Error {
  constructor(slug: string) {
    super(`Agent not found: "${slug}".`);
    this.name = 'AgentNotFoundError';
  }
}

export class AgentExistsError extends Error {
  constructor(slug: string) {
    super(`Agent already exists: "${slug}".`);
    this.name = 'AgentExistsError';
  }
}

export class NotInitializedError extends Error {
  constructor() {
    super('Afterglow has not been initialized. Run /afterglow init first.');
    this.name = 'NotInitializedError';
  }
}

export function assertValidSlug(slug: string): void {
  const ok = slug.length === 1 ? SLUG_RE_SINGLE.test(slug) : SLUG_RE.test(slug);
  if (!ok) throw new InvalidSlugError(slug);
}

/* --------------------------------------------------------------- */
/* Init / status                                                   */
/* --------------------------------------------------------------- */

export interface InitOptions {
  embeddingModel?: string;
}

export interface InitResult {
  root: string;
  created: string[];
  alreadyExisted: boolean;
}

const DEFAULT_CONFIG = (model: string) => `# Afterglow environment config
# Generated by /afterglow init — safe to edit.

embedding_model: ${model}
storage_root: ~/.claude/afterglow
created_at: ${new Date().toISOString()}
`;

export async function isInitialized(): Promise<boolean> {
  try {
    await fs.access(configPath());
    await fs.access(registryPath());
    return true;
  } catch {
    return false;
  }
}

export async function assertInitialized(): Promise<void> {
  if (!(await isInitialized())) throw new NotInitializedError();
}

export async function init(opts: InitOptions = {}): Promise<InitResult> {
  const embeddingModel = opts.embeddingModel ?? 'text-embedding-3-small';
  const created: string[] = [];

  const root = rootDir();
  const existed = await isInitialized();

  await mkdirIdempotent(root, created);
  await mkdirIdempotent(agentsDir(), created);
  await mkdirIdempotent(councilsDir(), created);

  if (!(await pathExists(configPath()))) {
    await fs.writeFile(configPath(), DEFAULT_CONFIG(embeddingModel), 'utf8');
    created.push(configPath());
  }
  if (!(await pathExists(registryPath()))) {
    await fs.writeFile(registryPath(), JSON.stringify({ version: 1, agents: [] }, null, 2) + '\n', 'utf8');
    created.push(registryPath());
  }

  return { root, created, alreadyExisted: existed };
}

/* --------------------------------------------------------------- */
/* Registry I/O                                                    */
/* --------------------------------------------------------------- */

export type AgentStatus = 'active' | 'learning' | 'paused' | 'draft' | 'archived';

export interface RegistryEntry {
  slug: string;
  name: string;
  role: string;
  status: AgentStatus;
  createdAt: string;
  trainedAt: string | null;
}

export interface Registry {
  version: 1;
  agents: RegistryEntry[];
}

export async function readRegistry(): Promise<Registry> {
  await assertInitialized();
  const raw = await fs.readFile(registryPath(), 'utf8');
  const parsed = JSON.parse(raw) as Registry;
  if (!parsed || parsed.version !== 1 || !Array.isArray(parsed.agents)) {
    throw new Error('registry.json is malformed.');
  }
  return parsed;
}

export async function writeRegistry(reg: Registry): Promise<void> {
  await fs.writeFile(registryPath(), JSON.stringify(reg, null, 2) + '\n', 'utf8');
}

export async function upsertRegistryEntry(entry: RegistryEntry): Promise<void> {
  const reg = await readRegistry();
  const idx = reg.agents.findIndex((a) => a.slug === entry.slug);
  if (idx >= 0) {
    reg.agents[idx] = entry;
  } else {
    reg.agents.push(entry);
    reg.agents.sort((a, b) => a.slug.localeCompare(b.slug));
  }
  await writeRegistry(reg);
}

export async function removeRegistryEntry(slug: string): Promise<void> {
  const reg = await readRegistry();
  reg.agents = reg.agents.filter((a) => a.slug !== slug);
  await writeRegistry(reg);
}

/* --------------------------------------------------------------- */
/* Agent folder                                                    */
/* --------------------------------------------------------------- */

export async function agentExists(slug: string): Promise<boolean> {
  return pathExists(agentDir(slug));
}

export async function createAgentSkeleton(slug: string): Promise<string[]> {
  await assertInitialized();
  assertValidSlug(slug);
  if (await agentExists(slug)) throw new AgentExistsError(slug);

  const created: string[] = [];
  await mkdirIdempotent(agentDir(slug), created);
  await mkdirIdempotent(knowledgeDir(slug), created);
  await mkdirIdempotent(embeddingsDir(slug), created);
  return created;
}

export async function readPersona(slug: string): Promise<Persona> {
  if (!(await agentExists(slug))) throw new AgentNotFoundError(slug);
  const raw = await fs.readFile(personaPath(slug), 'utf8');
  return JSON.parse(raw) as Persona;
}

export async function writePersona(slug: string, persona: Persona): Promise<void> {
  await fs.writeFile(personaPath(slug), JSON.stringify(persona, null, 2) + '\n', 'utf8');
}

export async function writeSystemPrompt(slug: string, body: string): Promise<void> {
  const path = systemPromptPath(slug);
  await ensureDir(dirname(path));
  await fs.writeFile(path, body.endsWith('\n') ? body : body + '\n', 'utf8');
}

export async function readSystemPrompt(slug: string): Promise<string> {
  return fs.readFile(systemPromptPath(slug), 'utf8');
}

export async function appendHistory(slug: string, line: string): Promise<void> {
  const path = historyLogPath(slug);
  await ensureDir(dirname(path));
  const ts = new Date().toISOString();
  await fs.appendFile(path, `${ts}  ${line}\n`, 'utf8');
}

/* --------------------------------------------------------------- */
/* History log parsing                                             */
/* --------------------------------------------------------------- */

export interface HistoryEvent {
  ts: string;
  message: string;
}

export async function readHistory(slug: string): Promise<HistoryEvent[]> {
  if (!(await agentExists(slug))) throw new AgentNotFoundError(slug);
  const path = historyLogPath(slug);
  let raw: string;
  try {
    raw = await fs.readFile(path, 'utf8');
  } catch {
    return [];
  }
  const lines = raw.split('\n').filter((l) => l.trim().length > 0);
  // Format: `${ISO timestamp}  ${message}`
  const out: HistoryEvent[] = [];
  for (const line of lines) {
    const m = line.match(/^(\S+)\s\s(.+)$/);
    if (m) out.push({ ts: m[1], message: m[2] });
    else out.push({ ts: '', message: line });
  }
  return out;
}

/* --------------------------------------------------------------- */
/* Consent / status workflow                                       */
/* --------------------------------------------------------------- */

export class NotSignedError extends Error {
  constructor(slug: string, currentStatus?: AgentStatus) {
    const stateHint = currentStatus ? ` (current: ${currentStatus})` : '';
    // For `paused` and `draft` we point users at two different remedies:
    //   - draft   → /afterglow sign     (consent not yet captured)
    //   - paused  → /afterglow resume   (consent still on file)
    // Both options are listed so the message stays useful when the caller
    // didn't pass currentStatus.
    super(
      `Agent "${slug}" is not active${stateHint}.\n` +
        `  · 처음 서명: /afterglow sign ${slug} --signer "..."\n` +
        `  · 이미 서명되어 있다면: /afterglow resume ${slug}`,
    );
    this.name = 'NotSignedError';
  }
}

export interface SignResult {
  signedAt: string;
  signer: string;
  previousStatus: RegistryEntry['status'];
  newStatus: RegistryEntry['status'];
}

export async function signConsent(
  slug: string,
  signer: string,
  note?: string,
): Promise<SignResult> {
  await assertInitialized();
  if (!(await agentExists(slug))) throw new AgentNotFoundError(slug);

  const reg = await readRegistry();
  const entry = reg.agents.find((a) => a.slug === slug);
  if (!entry) throw new AgentNotFoundError(slug);
  const previousStatus = entry.status;

  const signedAt = new Date().toISOString();
  const block =
    `\n## 서명\n\n` +
    `- 서명자: ${signer}\n` +
    `- 시각: ${signedAt}\n` +
    (note ? `- 메모: ${note}\n` : '');
  await fs.appendFile(consentPath(slug), block, 'utf8');

  entry.status = 'active';
  entry.trainedAt = entry.trainedAt ?? signedAt;
  await writeRegistry(reg);

  return { signedAt, signer, previousStatus, newStatus: 'active' };
}

export async function pauseAgent(slug: string): Promise<RegistryEntry['status']> {
  await assertInitialized();
  if (!(await agentExists(slug))) throw new AgentNotFoundError(slug);
  const reg = await readRegistry();
  const entry = reg.agents.find((a) => a.slug === slug);
  if (!entry) throw new AgentNotFoundError(slug);
  const prev = entry.status;
  entry.status = 'paused';
  await writeRegistry(reg);
  return prev;
}

export async function resumeAgent(slug: string): Promise<RegistryEntry['status']> {
  await assertInitialized();
  if (!(await agentExists(slug))) throw new AgentNotFoundError(slug);
  const reg = await readRegistry();
  const entry = reg.agents.find((a) => a.slug === slug);
  if (!entry) throw new AgentNotFoundError(slug);
  const prev = entry.status;
  entry.status = 'active';
  await writeRegistry(reg);
  return prev;
}

export async function getStatus(slug: string): Promise<RegistryEntry['status']> {
  const reg = await readRegistry();
  const entry = reg.agents.find((a) => a.slug === slug);
  if (!entry) throw new AgentNotFoundError(slug);
  return entry.status;
}

/**
 * Gate for `afterglow_ask` (and council). Allows only `active` agents.
 * Bypass for tests / debug: AFTERGLOW_ALLOW_DRAFT=1 disables the gate.
 * Archived agents are always blocked (must be restored first).
 */
export async function assertActive(slug: string): Promise<void> {
  const status = await getStatus(slug);
  if (status === 'archived') throw new ArchivedAgentError(slug);
  if (process.env.AFTERGLOW_ALLOW_DRAFT === '1') return;
  if (status !== 'active') throw new NotSignedError(slug, status);
}

/* --------------------------------------------------------------- */
/* Archive / restore                                               */
/* --------------------------------------------------------------- */

export class ArchivedAgentError extends Error {
  constructor(slug: string) {
    super(`Agent "${slug}" is archived. Restore it first: /afterglow archive ${slug} --action restore`);
    this.name = 'ArchivedAgentError';
  }
}

export class NotArchivedError extends Error {
  constructor(slug: string) {
    super(`Agent "${slug}" is not archived. Nothing to restore.`);
    this.name = 'NotArchivedError';
  }
}

export class ArchiveTargetExistsError extends Error {
  constructor(path: string) {
    super(`Archive target already exists: ${path}. Refusing to overwrite.`);
    this.name = 'ArchiveTargetExistsError';
  }
}

export class RestoreTargetExistsError extends Error {
  constructor(path: string) {
    super(`Restore target already exists: ${path}. An active agent with the same slug is in the way.`);
    this.name = 'RestoreTargetExistsError';
  }
}

export interface ArchiveResult {
  slug: string;
  movedFrom: string;
  movedTo: string;
  previousStatus: AgentStatus;
  archivedAt: string;
}

export async function archiveAgent(slug: string): Promise<ArchiveResult> {
  await assertInitialized();
  if (!(await agentExists(slug))) throw new AgentNotFoundError(slug);
  const reg = await readRegistry();
  const entry = reg.agents.find((a) => a.slug === slug);
  if (!entry) throw new AgentNotFoundError(slug);
  if (entry.status === 'archived') {
    throw new Error(`Agent "${slug}" is already archived.`);
  }

  await ensureDir(archiveDir());
  const target = archivedAgentDir(slug);
  if (await pathExists(target)) throw new ArchiveTargetExistsError(target);

  const source = agentDir(slug);
  await fs.rename(source, target);

  const previousStatus = entry.status;
  const archivedAt = new Date().toISOString();
  entry.status = 'archived';
  await writeRegistry(reg);

  return {
    slug,
    movedFrom: source,
    movedTo: target,
    previousStatus,
    archivedAt,
  };
}

export interface RestoreResult {
  slug: string;
  movedFrom: string;
  movedTo: string;
  newStatus: AgentStatus;
  restoredAt: string;
}

/**
 * Restore an archived agent back to agents/<slug>/. Lands in `paused` —
 * the user must explicitly re-sign or call resume to reach `active`.
 * This avoids surprise activations after months on the shelf.
 */
export async function restoreAgent(slug: string): Promise<RestoreResult> {
  await assertInitialized();
  const reg = await readRegistry();
  const entry = reg.agents.find((a) => a.slug === slug);
  if (!entry) throw new AgentNotFoundError(slug);
  if (entry.status !== 'archived') throw new NotArchivedError(slug);

  const source = archivedAgentDir(slug);
  if (!(await pathExists(source))) {
    throw new Error(`Archived folder missing: ${source}. Registry says archived but data is gone.`);
  }
  const target = agentDir(slug);
  if (await pathExists(target)) throw new RestoreTargetExistsError(target);

  await ensureDir(agentsDir());
  await fs.rename(source, target);

  const restoredAt = new Date().toISOString();
  entry.status = 'paused';
  await writeRegistry(reg);

  return {
    slug,
    movedFrom: source,
    movedTo: target,
    newStatus: 'paused',
    restoredAt,
  };
}

export async function listArchivedSlugs(): Promise<string[]> {
  try {
    const entries = (await fs.readdir(archiveDir(), { withFileTypes: true })) as unknown as {
      name: string;
      isDirectory: () => boolean;
    }[];
    return entries.filter((e) => e.isDirectory()).map((e) => e.name).sort();
  } catch {
    return [];
  }
}

/* --------------------------------------------------------------- */
/* Internals                                                       */
/* --------------------------------------------------------------- */

export async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function ensureDir(p: string): Promise<void> {
  await fs.mkdir(p, { recursive: true });
}

async function mkdirIdempotent(p: string, log: string[]): Promise<void> {
  const existed = await pathExists(p);
  await ensureDir(p);
  if (!existed) log.push(p);
}
