/**
 * Filesystem layout owner for ~/.claude/afterglow/
 *
 *   ~/.claude/afterglow/
 *   ├─ config.yml                ← env config (embedding model, storage root, …)
 *   ├─ registry.json             ← index of all agents
 *   ├─ councils/                 ← council + peer-ask transcripts (markdown)
 *   └─ agents/<slug>/
 *      ├─ persona.json
 *      ├─ system-prompt.md
 *      ├─ mcp-allowlist.yml
 *      ├─ consent.md
 *      ├─ history.log
 *      ├─ knowledge/             ← raw source files (PDF / md / txt / …)
 *      └─ embeddings/            ← derived RAG index (jsonl chunks for the PoC)
 */
import { promises as fs } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import type { Persona } from './persona.js';

/**
 * Resolved on every call (not at module load) so tests can flip
 * AFTERGLOW_ROOT per-test without re-importing the module.
 */
export function rootDir(): string {
  const envRoot = process.env.AFTERGLOW_ROOT;
  if (envRoot) return resolve(envRoot);
  return join(homedir(), '.claude', 'afterglow');
}

export function configPath(): string {
  return join(rootDir(), 'config.yml');
}

export function registryPath(): string {
  return join(rootDir(), 'registry.json');
}

export function councilsDir(): string {
  return join(rootDir(), 'councils');
}

export function agentsDir(): string {
  return join(rootDir(), 'agents');
}

export function agentDir(slug: string): string {
  return join(agentsDir(), slug);
}

export function personaPath(slug: string): string {
  return join(agentDir(slug), 'persona.json');
}

export function systemPromptPath(slug: string): string {
  return join(agentDir(slug), 'system-prompt.md');
}

export function consentPath(slug: string): string {
  return join(agentDir(slug), 'consent.md');
}

export function historyLogPath(slug: string): string {
  return join(agentDir(slug), 'history.log');
}

export function knowledgeDir(slug: string): string {
  return join(agentDir(slug), 'knowledge');
}

export function embeddingsDir(slug: string): string {
  return join(agentDir(slug), 'embeddings');
}

/* --------------------------------------------------------------- */
/* Slug validation                                                 */
/* --------------------------------------------------------------- */

const SLUG_RE = /^[a-z0-9][a-z0-9-]{0,30}[a-z0-9]$/;
const SLUG_RE_SINGLE = /^[a-z0-9]$/;

export class InvalidSlugError extends Error {
  constructor(slug: string) {
    super(`Invalid slug: "${slug}". Use 1-32 lowercase letters/digits/hyphens, starting and ending with a letter or digit.`);
    this.name = 'InvalidSlugError';
  }
}

export class AgentNotFoundError extends Error {
  constructor(slug: string) {
    super(`Agent not found: "${slug}".`);
    this.name = 'AgentNotFoundError';
  }
}

export class AgentExistsError extends Error {
  constructor(slug: string) {
    super(`Agent already exists: "${slug}".`);
    this.name = 'AgentExistsError';
  }
}

export class NotInitializedError extends Error {
  constructor() {
    super('Afterglow has not been initialized. Run /afterglow init first.');
    this.name = 'NotInitializedError';
  }
}

export function assertValidSlug(slug: string): void {
  const ok = slug.length === 1 ? SLUG_RE_SINGLE.test(slug) : SLUG_RE.test(slug);
  if (!ok) throw new InvalidSlugError(slug);
}

/* --------------------------------------------------------------- */
/* Init / status                                                   */
/* --------------------------------------------------------------- */

export interface InitOptions {
  embeddingModel?: string;
}

export interface InitResult {
  root: string;
  created: string[];
  alreadyExisted: boolean;
}

const DEFAULT_CONFIG = (model: string) => `# Afterglow environment config
# Generated by /afterglow init — safe to edit.

embedding_model: ${model}
storage_root: ~/.claude/afterglow
created_at: ${new Date().toISOString()}
`;

export async function isInitialized(): Promise<boolean> {
  try {
    await fs.access(configPath());
    await fs.access(registryPath());
    return true;
  } catch {
    return false;
  }
}

export async function assertInitialized(): Promise<void> {
  if (!(await isInitialized())) throw new NotInitializedError();
}

export async function init(opts: InitOptions = {}): Promise<InitResult> {
  const embeddingModel = opts.embeddingModel ?? 'text-embedding-3-small';
  const created: string[] = [];

  const root = rootDir();
  const existed = await isInitialized();

  await mkdirIdempotent(root, created);
  await mkdirIdempotent(agentsDir(), created);
  await mkdirIdempotent(councilsDir(), created);

  if (!(await pathExists(configPath()))) {
    await fs.writeFile(configPath(), DEFAULT_CONFIG(embeddingModel), 'utf8');
    created.push(configPath());
  }
  if (!(await pathExists(registryPath()))) {
    await fs.writeFile(registryPath(), JSON.stringify({ version: 1, agents: [] }, null, 2) + '\n', 'utf8');
    created.push(registryPath());
  }

  return { root, created, alreadyExisted: existed };
}

/* --------------------------------------------------------------- */
/* Registry I/O                                                    */
/* --------------------------------------------------------------- */

export interface RegistryEntry {
  slug: string;
  name: string;
  role: string;
  status: 'active' | 'learning' | 'paused' | 'draft';
  createdAt: string;
  trainedAt: string | null;
}

export interface Registry {
  version: 1;
  agents: RegistryEntry[];
}

export async function readRegistry(): Promise<Registry> {
  await assertInitialized();
  const raw = await fs.readFile(registryPath(), 'utf8');
  const parsed = JSON.parse(raw) as Registry;
  if (!parsed || parsed.version !== 1 || !Array.isArray(parsed.agents)) {
    throw new Error('registry.json is malformed.');
  }
  return parsed;
}

export async function writeRegistry(reg: Registry): Promise<void> {
  await fs.writeFile(registryPath(), JSON.stringify(reg, null, 2) + '\n', 'utf8');
}

export async function upsertRegistryEntry(entry: RegistryEntry): Promise<void> {
  const reg = await readRegistry();
  const idx = reg.agents.findIndex((a) => a.slug === entry.slug);
  if (idx >= 0) {
    reg.agents[idx] = entry;
  } else {
    reg.agents.push(entry);
    reg.agents.sort((a, b) => a.slug.localeCompare(b.slug));
  }
  await writeRegistry(reg);
}

export async function removeRegistryEntry(slug: string): Promise<void> {
  const reg = await readRegistry();
  reg.agents = reg.agents.filter((a) => a.slug !== slug);
  await writeRegistry(reg);
}

/* --------------------------------------------------------------- */
/* Agent folder                                                    */
/* --------------------------------------------------------------- */

export async function agentExists(slug: string): Promise<boolean> {
  return pathExists(agentDir(slug));
}

export async function createAgentSkeleton(slug: string): Promise<string[]> {
  await assertInitialized();
  assertValidSlug(slug);
  if (await agentExists(slug)) throw new AgentExistsError(slug);

  const created: string[] = [];
  await mkdirIdempotent(agentDir(slug), created);
  await mkdirIdempotent(knowledgeDir(slug), created);
  await mkdirIdempotent(embeddingsDir(slug), created);
  return created;
}

export async function readPersona(slug: string): Promise<Persona> {
  if (!(await agentExists(slug))) throw new AgentNotFoundError(slug);
  const raw = await fs.readFile(personaPath(slug), 'utf8');
  return JSON.parse(raw) as Persona;
}

export async function writePersona(slug: string, persona: Persona): Promise<void> {
  await fs.writeFile(personaPath(slug), JSON.stringify(persona, null, 2) + '\n', 'utf8');
}

export async function writeSystemPrompt(slug: string, body: string): Promise<void> {
  const path = systemPromptPath(slug);
  await ensureDir(dirname(path));
  await fs.writeFile(path, body.endsWith('\n') ? body : body + '\n', 'utf8');
}

export async function readSystemPrompt(slug: string): Promise<string> {
  return fs.readFile(systemPromptPath(slug), 'utf8');
}

export async function appendHistory(slug: string, line: string): Promise<void> {
  const path = historyLogPath(slug);
  await ensureDir(dirname(path));
  const ts = new Date().toISOString();
  await fs.appendFile(path, `${ts}  ${line}\n`, 'utf8');
}

/* --------------------------------------------------------------- */
/* Internals                                                       */
/* --------------------------------------------------------------- */

export async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function ensureDir(p: string): Promise<void> {
  await fs.mkdir(p, { recursive: true });
}

async function mkdirIdempotent(p: string, log: string[]): Promise<void> {
  const existed = await pathExists(p);
  await ensureDir(p);
  if (!existed) log.push(p);
}
